In [48]:
import numpy as np
import scipy as sp
np.random.seed(22)
n = 500
m = 5000
data = np.random.uniform(0, 1, size=(m, n))
data.reshape(m, n)

array([[0.20846054, 0.48168106, 0.42053804, ..., 0.29423118, 0.40776007,
        0.74514439],
       [0.9023332 , 0.65206676, 0.08046449, ..., 0.67659699, 0.41244338,
        0.23062308],
       [0.59529911, 0.27612519, 0.68172998, ..., 0.82754857, 0.27678105,
        0.29894817],
       ...,
       [0.57489516, 0.77782137, 0.6915006 , ..., 0.84629992, 0.48255577,
        0.14937382],
       [0.64272261, 0.57195532, 0.53934089, ..., 0.4154515 , 0.3381279 ,
        0.83200386],
       [0.2557776 , 0.75631123, 0.51107757, ..., 0.81500714, 0.06380435,
        0.50284429]])

In [50]:
sample = np.zeros((m , 9))
intervals = np.linspace (0, 1, 10)
print(intervals)
for i in range (m):
    counts, _ = np. histogram (data[i], bins=intervals)
    sample[i] = counts
    if i in [0,1,2, 4999]:
        print(counts)
        
print(sample)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[68 57 39 53 62 59 59 53 50]
[53 62 55 62 57 45 66 52 48]
[53 64 57 55 64 52 48 63 44]
[70 53 64 45 48 47 50 65 58]
[[68. 57. 39. ... 59. 53. 50.]
 [53. 62. 55. ... 66. 52. 48.]
 [53. 64. 57. ... 48. 63. 44.]
 ...
 [55. 53. 54. ... 59. 63. 59.]
 [52. 59. 54. ... 61. 44. 59.]
 [70. 53. 64. ... 50. 65. 58.]]


In [51]:
p = [1 / 9 for i in range(9)]
mcounts = [p[i] * n for i in range(9)]
mcounts

[55.55555555555555,
 55.55555555555555,
 55.55555555555555,
 55.55555555555555,
 55.55555555555555,
 55.55555555555555,
 55.55555555555555,
 55.55555555555555,
 55.55555555555555]

In [52]:
D = (1 / n) * np.sum(np.abs(sample - 55.555555556), axis=1)
np.sort(D)

array([0.02444444, 0.02888889, 0.03111111, ..., 0.20711111, 0.21111111,
       0.21911111])

In [54]:
alpha_ = [0.1, 0.05, 0.01]
quantiles_alpha = np.quantile(D, [1 - alpha for alpha in alpha_ ], method ='nearest')
quantiles_alpha

array([0.13688889, 0.14711111, 0.16888889])

In [57]:
np.random.seed(100)
data1 = np.random.uniform(0, 1, n)
counts1, _ = np.histogram(data1, bins=intervals)
D1 = (1 / n) * np.sum(np.abs(counts1 - 55.555555556))
D1

0.098666666664

In [61]:
np.random.seed(99)
ksi = np.random.uniform(0, 1, n)
data2 = np.sqrt(ksi)
counts2, _ = np.histogram(data2, bins=intervals )
D2 = (1 / n) * np.sum(np.abs(counts2 - 55.555555556))
D2

0.520888888888

In [64]:
np.random.seed(98)
ksi = np.random.uniform(0, 1, n)
data3 = 1 - np.sqrt(ksi)
counts3, _ = np.histogram(data3, bins = intervals )
D3 = (1 / n) * np.sum(np.abs(counts3 - 55.555555556))
D3

0.512888888888

In [65]:
data4 = np.random.beta(0.25, 0.75, n)
counts4, _ = np.histogram(data4, bins=intervals )
D4 = (1 / n) * np.sum(np.abs(counts4 - 55.555555556))
D4

0.7315555555600001